### ISSUE TITLE
Developer Experience on Devices

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#1012]
### Description

Epic to explore improvements to the experience of developing for devices, rather than develop on the cloud and then snapshot and deploy to a device we are considering options around:

- [ ] Enable editor for a given device (connectivity would be the users responsibility)
- [x] A node-red plugin to pull flows and config from Node-RED up to FlowForge - shipped as part of 1.1.0
- [ ] Routing connectivity between a device editor and the cloud using something like ngrok

**Comment by sammachin** [comment]
This would also help to solve a number of issues with certain nodes not being compatible with running on the cloud but having valid use cases on devices.

**Comment by sammachin** [comment]
Related to this experience the user may want to control the runtime of a specific device to start and stop the flows

**Comment by joepavitt** [comment]
High level UX I would envision here:

- Flowforge Editor on Device
- Can create a snapshot on device
- Central FlowForge enables deployment of that snapshot to any number of devices

**Comment by knolleary** [comment]
We shipped one of the concepts from this epic as part of 1.1.0 - the Node-RED Tools plugin. I'm putting this epic back to the Product board so its other concepts can be considered. We'll probably want to split them into their own items.

**Comment by ZJvandeWeg** [comment]
I've had a request for enabling a "debug mode" from FlowForge, to enable the editor and directly connect to it.

**Comment by MarianRaphael** [comment]
Activities tracked in own epics.
For more information, please see the following issues:
https://github.com/flowforge/flowforge/issues/1821
https://github.com/flowforge/flowforge/issues/1703
