### ISSUE TITLE
Enable search over large data sets

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1065]
### Description

**As a:** Admin User

**I want to:** be able to query users of the FlowForge Platform

**So that:** I can find particular users/teams in order to assist with support tickets

Currently, the [`ff-data-table`](https://flowforge.github.io/forge-ui-components/#ff-data-table) component filtering only supports filtering of locally loaded content. Given that our API uses pagination, when we have large data sets, the filtering is limited to searching only the already loaded data.

As a result, we need to implement the following path:

1. As a user types into the filter input, call the relevant API, filtering by the search term, where that search term could cover any of the parameters detailed in the table. The `search-fields` property on `ff-data-table` will also provide data as to which fields can be assessed when filtering.
2. Given the response from the API, populate the table with the provided data.

### Acceptance Criteria

- [x] API - Add `?query=` support to paginated APIs (#1104)
- [x] FE - Call the API when a user types into the filter box (#1110)
- [x] FE - Filter the Admin > Users table as per the result of the new search API functionality (#1110)

**Comment by hardillb** [comment]
We don't have any entities on Staging that are more than one page in a table so can't easily test this at the moment

**Comment by knolleary** [comment]
Closing as all prs are merged

**Comment by Steve-Mcl** [comment]
Added 100 random users (bash script below for future testing/reference). 

Some slight niggles - but is working...
* table empties and reloads with every character typed
* when clicking `more` the last entry is shown but the `more` button is still visible & then disappears after 1 more click.
* sorting is client side only (e.g. sorting by name does not reveal the last user `Zumba Zulu`)

bash script for generating names from "Arron Aardvark" to "Zumba Zulu" (all names are auto generated / fake)

```bash
NAMES=( "Arron Aardvark" "Leilani Stewart" "Joselyn Ramos" "Ramon Conrad" "Jakayla Mccann" "Jaslyn Nolan" "Donavan Mitchell" "Aden Montgomery" "Larissa Park" "Sawyer Robles" "Irvin Rios" "Karina Lee" "Alexus Velazquez" "Alessandro Bryant" "Robert Poole" "Cruz Clarke" "Maxim Warren" "Campbell Beltran" "Esteban Michael" "Monica Reid" "Zachary Ewing" "Briana Moreno" "Alison Ayers" "Josephine Alvarez" "Keira Burnett" "Roman Curtis" "Angel Knox" "Lucian Mueller" "Clarence Moran" "Devan Pace" "Mina Lang" "Aditya Holmes" "Dario Mccarthy" "Mayra Fry" "Stanley Melendez" "Chana Stevens" "Brielle Duke" "Adelyn Hickman" "Vivian Lynch" "Kamron Nixon" "Micah Hodges" "Frida Hebert" "Joshua Ward" "Gia Brandt" "Marco Pierce" "Hayley Shah" "Kelton Stanton" "Serenity Cantu" "Amir Joyce" "Raven Mendez" "Kimora Maddox" "Killian James" "Mark Rojas" "Kadin Craig" "Kyra Weiss" "Livia Fry" "Emmett Mclaughlin" "Carly Nicholson" "Katherine Wolfe" "Bailee Krause" "Charlie Ayers" "Jada Riddle" "Branden Weaver" "Jocelynn Murphy" "Megan Figueroa" "Layton Dodson" "Corbin Reilly" "Frances Boone" "Zara Ayala" "Ari Carpenter" "Camryn Patrick" "Kyle Norton" "Jaylee Hamilton" "Javon Mccann" "Ricky Simmons" "Rudy Baldwin" "Adelaide Daugherty" "Josephine Trujillo" "Izaiah Blevins" "Bethany Yang" "Veronica Garrison" "Natasha Lambert" "Myla Richmond" "Makhi Floyd" "Douglas Cruz" "Erika Moore" "Madalyn Salinas" "Madeline Gates" "Tucker Molina" "Kathleen Randolph" "Saniya Greene" "Leila Avery" "Cannon Waller" "Abdullah Solomon" "Conrad Weiss" "Marvin Schroeder" "Kyra Torres" "Tori Baxter" "Anaya Ware" "Adelyn Ponce" "Eliza Swanson" "Zumba Zulu" )
for i in ${!NAMES[@]}; do
  echo .
  name="${NAMES[$i]}"
  email_template="${name}@localhost.local"
  username_template="${name,,}"
  search_string=" "
  replace_string="-"
  username=${username_template/$search_string/$replace_string}
  email="${username}@localhost.local"
  password="testtest"
  echo "Creating ${name}, emails address: ${email} username: ${username}"
  curl 'http://192.168.xx.xx:3000/api/v1/users' \
    -H 'Accept: application/json, text/plain, */*' \
    -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,es;q=0.7' \
    -H 'Cache-Control: no-cache' \
    -H 'Connection: keep-alive' \
    -H 'Content-Type: application/json' \
    -H 'Cookie: sid=ffu_xxxxxxxxxxxxxxxxx; connect.sid=s%3AWxxxxxxxxxxxxxxxx' \
    -H 'Origin: http://192.168.xx.xx:3000' \
    -H 'Pragma: no-cache' \
    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
    --data-raw "{\"name\":\"${name} DELETE ME\",\"username\":\"${username}\",\"email\":\"${email}\",\"password\":\"${password}\",\"isAdmin\":false,\"createDefaultTeam\":false}" \
    --compressed \
    --insecure
  read -p "Created user ${username}" -t 0.5
done
```

**Comment by knolleary** [comment]
Ok - we didn't consider sorting when it came to this. Please raise an issue.
