### ISSUE TITLE
Add Filtering to Audit Log Screens

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1448]
### Epic

#1166

### Description

**As a:** an admin user or team owner

**I want to:** be able to filter my Audit Log / Activity so that I can easily get a picture of when particular events took place 

**So that:** I can easily debug issues or backtrack when potentially breaking changes may have been made.

### Which customers would this be available to

None

### Acceptance Criteria

**Completed in `feat-1468-audit-filtering`:**
- [x] Audit Log Component doesn't internally call API structure, but instead just accepts an Array of entires to render (so we can filter outside of the rendering component)
- [x] Implement a search bar that enables string querying over all of the available activity entries

**Todo:**:
- [ ] Pre-defined checkboxes for different event types & characteristics.

### Tasks

 - [x] #1489
 - [ ] Implement async API filtering/searching from the first task

**Comment by joepavitt** [comment]
Progress in Iteration 1.2, client-side filtering only. Would need API-driven filtering/searching ideally to be useful

https://user-images.githubusercontent.com/99246719/209335681-041cb62d-cb53-4e57-aa71-f23604855af7.mov

**Comment by joepavitt** [comment]
Awaiting server-side API functionality from https://github.com/flowforge/flowforge/issues/1489 before continuing this work.

**Comment by robmarcer** [comment]
@knolleary do we expect this feature to make the cut for the 1.3 release?

**Comment by joepavitt** [comment]
> @knolleary do we expect this feature to make the cut for the 1.3 release?

@robmarcer incredibly unlikely at the moment, as Pez is out this week too.

**Comment by knolleary** [comment]
@robmarcer @joepavitt I am picking up the backend work needed by this today. We will review where it is at tomorrow morning.

**Comment by robmarcer** [comment]
No problem @knolleary, I'll leave it out of the blog etc for now and see where we are tomorrow.
