### ISSUE TITLE
Provide several days trial

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1471]
### Description

For a customer of FlowForge Cloud it might be challenging to understand the value of our offering. When creating a team, the first thing they're greeted with is a checkout page. They're likely not aware what the value is, and might want to try before they buy.

For FlowForge Cloud there's an opportunity to allow a trial for a number of days. Stripe allows [`trial_period_days`](https://stripe.com/docs/api/subscriptions/create#create_subscription-trial_period_days) to be set. This change should allow anyone, even without coupon, to have a risk free onboarding experience.

The trial should work for:
* 1 small project
* ~once per team~ - For each users firs team

----

## Tracking

Summary of the comment thread below.

### MVP

- [x] Technical Implementation - https://github.com/flowforge/flowforge/pull/1544
  - [x] Add yaml config to configure a dollar amount to be applies to new subscriptions
  - [x] Apply a credit to the stripe customer when a user creates their first team (and if they are not a member of any team)
  - [x] Add current credit balance to team billing UI
  - [x] Add current credit balance to create project page UI
  - [x] Billing documentation updates on how to make use of this feature

### Follow ups
 - [x] https://github.com/flowforge/flowforge/issues/1552
 - [ ] https://github.com/flowforge/CloudProject/issues/115 (private repo)
 - [x] https://github.com/flowforge/flowforge/issues/1521
    - [x] #1548
        > This sets up your team for billing. You are only charged when creating a Project.
    - [x] #1549
        > As this is your first FlowForge team, we’re giving you free credit equivalent to a Small Project for one month’. This will be applied to your next Stripe invoice.
    - [x] #1550
    - [x] #1551
 - [x] https://github.com/flowforge/CloudProject/issues/118 (Private repo)
 - [x] https://github.com/flowforge/CloudProject/issues/119 (Private repo)
 - [ ] Marketing and website changes around free trials - was discussed in https://github.com/flowforge/flowforge/issues/1521
 - [x] Demo to team - Recording in Slack

**Comment by Pezmc** [comment]
Ideally, I strongly believe that the customer should be able to start a free trial without having to go through the checkout flow in the first place, if we can mitigate any drawbacks.

My theory is that by reducing the barrier to seeing [Node-RED](https://nodered.org/) running, we increase the amount of free trials, particularly for people kicking the tyres and trying to understand the offering by poking at it (rather than reading docs/marketing), and that leads to increased _net_ conversions due to greater understanding, though likely with a lower conversion _rate_.

i.e.

```
[Create Account] -> [Create Team] -> [Create Small Project] -> [...three days passes...] -> [Project is stopped unless CC has been added]
```

Instead of:

```
[Create Account] -> [Create Team] -> [Stripe Checkout Flow] -> [Start free trial] -> [Create small project] -> [...three days passes...] -> [CC is auto charged]
```

This might be more technical work (e.g. we handle trials outside of Stripe or create the trial subscription using Stripe API calls in the background), but believe it's a much less jarring experience for the user. That being said, it does make abuse of the free trial slightly more likely.

Pros:
 - Lower barrier to entry -> should increase sign ups

Cons and possible mitigation suggestions:
 - User has to return to add CC information or the project is stopped, extra work later
    - Add banner to top of page warning when trial expires and allowing CC info to be added at any time
    - Email warning before free trial expires with prompt to add CC
 - Possible abuse of free trials
    - Abuse detection/rate limiting based on IP/email/other
    - Limit project size
    - Limit number to number of projects
    - Limit to free trial teams per account
    - Add a special "tiny" project size only for free trials
    - Slack/email reports of trial signups with power to shutdown
 - More complex technical implementation
    - Use Stripe API to handle logic wherever possible
 - Higher number of trials means more costs spent on trials
    - Hopefully offset by increased conversions

**Comment by ZJvandeWeg** [comment]
> Ideally, I strongly believe that the customer should be able to start a free trial without having to go through the checkout flow in the first place, if we can mitigate any drawbacks.

I'd say that's a second iteration, not this one. I've reached out to Stripe to join the beta for it: https://stripe.com/docs/payments/checkout/free-trials. However, I don't want to overengineer it right now.

From the docs that Stripe has: https://stripe.com/docs/billing/subscriptions/trials#combining-trials-with-metered-prices it seems like just providing a 14 day trial period is something we can ship fast with metered billing.

So let's iterate and build an understanding if free trails with Credit card work, and when they convincingly do we take the next step.

**Comment by knolleary** [comment]
@Pezmc and I have concluded that Stripe Trials are not suitable for what we want to achieve, given our existing subscription model.

 - Stripe Trials apply to the whole subscription - they set the subscription amount to $0 for the trial duration
 - There is no way to have a Trial where the user gets a single item for $0 during the trial, but they pay normal price for anything else they create during the trial (on the same subscription).

If the goal here is to allow a user to create a project without being charged, or not being at a financial loss, the most pragmatic way of achieving that is via coupons.

This is not quite the same as giving them a small project for 14 days - but will be a discount for the first month usage and can be set to whatever value we chose.

We already support providing a coupon as part of the sign-up link. The proposal here is to allow `flowforge.yml` to provide a default coupon code that will be applied when a new subscription is created. The user will see the coupon applied on the checkout page of Stripe.

Some additional logic will be needed to protect this from abuse:

 - The coupon should only be applied when a user is creating their *first* team. If they are already in a team, no coupon should be applied.
 - The FF UI should make clear to the user if a coupon will be applied and what discount that will provide. As those details will be set in stripe, the admin will need to provide suitable text for this message via `flowforge.yml` alongside the actual coupon code.

We need to design where we'll show this information. The coupon is applied at Subscription setup as part of Team creation. The fact they have a discount available to them becomes relevant when they want to create a Project. We need to think about how to communicate clearly at this point in time that the coupon/discount has been applied.

### UX ideas

- **Option 1**: After creating team, redirect straight to 'create project' page with banner reinforcing message about coupon/discount
- **Options 2**: Add banner message to 'create project' page if all of these conditions apply:
    - if coupon has been configured in flowforge.yml
    - it is within first month of team creation
    - no projects yet created

**Comment by ZJvandeWeg** [comment]
@knolleary Why not remove the team subscription? It's not a billable entity, it should not be there. A customer could just have multiple projects attached.

**Comment by Pezmc** [comment]
@ZJvandeWeg We can remove the team _product_, but will always need one or many _subscriptions_ tied at a customer or team level.

The set-up right now is that each flowforge team has it's own stripe customer and stripe subscription, this means each team can be billed to a different credit card/person. However we also currently add a free product, called "team" to each subscription. I believe it was built this way as up until very recently it was intended for their to be team levels (#733, https://github.com/flowforge/flowforge/issues/1418) too.

So while we can remove the team _product_, at some point in the flow we still need to create a subscription object (tied to a customer, team or per project); and it's that subscription object that a stripe trial is tied to. To have a stripe trial for a single project, we'd need to have multiple stripe subscriptions per team, which are all started/stopped/billed independently, far from ideal for the user.

Assuming we want to each team to be able to be billed to a different card, the only way to implement a trial for a single project would be to handle the trial logic ourselves, which has [regulation requirements](https://support.stripe.com/questions/2020-visa-trial-subscription-requirement-changes-guide). Which is why @knolleary and I proposed adding credit to accounts (via a coupon) at first signup to meet the ultimate business objective of allowing new customers to try out flowforge easily at no cost.

**Comment by Pezmc** [comment]
We're moving forward with applying free trial for the first project for new customers to FF Cloud (or other deployment if configured).

**Messaging**: presented as a free X day trial of a small project
**Technically**: Implemented as a dollar value coupon applied to the subscription with a value equivalent to X days of the project

### Tasks:

MVP:
 - [ ] Decide specific amount of days to cover and whether this applies to each team
 - [ ] Add yaml config to enable free trials and tie them to a specific project level
 - [ ] When creating the first subscription for a team, apply a coupon behind the scenes

Follow ups
 - [ ] UX improvements (options 2)
     - [ ] Add banner message to 'create project' page if a coupon is active and this it the first project
     - [ ] Adjust the costs on the create project page to reference the trial
  - [ ] Marketing around free trials

**Comment by Pezmc** [comment]
While implementing coupons, I stumbled upon several notable downsides in preliminary testing, and have decided with @knolleary to change the **technical** implementation slightly and use customer credit balance instead. In terms of our communication, we can still talk about a free trial and credit,  but in the back-end it's now a customer credit balance.

An overview of the three options and why free trials and coupons are unsuitable:

1. Free Trials
    - Use the Stripe inbuilt free trial functionality to add a free trial to a customers first subscription. Full details [above](https://github.com/flowforge/flowforge/issues/1471#issuecomment-1371163674).
    - Key Pro:
       - The trial status is visible in Stripes UI and checkout process
    - **Blocker**:
        - Trials can only apply to the whole subscription, FF has multiple projects per subscription, thus any free trial period would apply to an all added projects.
2. Coupons
   - Apply a coupon for the dollar amount of a small project for one month. Full details [above](https://github.com/flowforge/flowforge/issues/1471#issuecomment-1372184861).
   - Stripe applies the coupon to the first project created "using the coupon up”
   - Key Downsides:
        - Not visible to customer in stripe flows at all
   - **Blocker**:
        - If the first project is deleted or suspended, the balance is permanently lost. 
        This means it's not possible to change stack, or rename a project, which require suspension / deletion and re-creation.
3. Credit Balance - New approach
    - When a customer creates their first team, add a dollar credit balance to the stripe customer.
    - The balance is used up when the customer adds their first project.
    - Key Pros:
      - If the balance is refunded during pro-ration calculations (e.g. when deleting or suspending a project), it persists, ready to be used on the next invoice.
         To a customer, this means they are free to use the balance in any way they see fit.
      - We can query the current balance and display it in the UI on the team billing and create a project pages.
    - Key Downsides
      -  Cannot be expired. 
          - Mitigation: Exposure is limited to $10 per team
          - Mitigation: The balance is only applied for each users first team they are a member of
       - Not visible to customer in stripe flows at all
          - Mitigation: Add it to our UI on the create a project and team billing pages

The above pros of credit balance and that we can mitigate the key downsides is why we're moving to this new approach.

The to-do list for this project is now as follows:

### MVP

 - [ ] Add yaml config to configure a dollar amount to be applies to new subscriptions
- [ ] Apply a credit to the stripe customer when a user creates their first team (and if they are not a member of any team)
- [ ] Add current credit balance to team billing UI
- [ ] Add current credit balance to create project page UI
- [ ] Billing documentation updates on how to make use of this feature

### Follow ups
 - [ ] UX improvements - https://github.com/flowforge/flowforge/issues/1521
 - [ ] Marketing around free trials - being discussed in https://github.com/flowforge/flowforge/issues/1521
 - [ ] Demo to team

**Comment by knolleary** [comment]
Reopening as this was auto-closed by merging the initial PR.

We will review the status of the follow up items over the next couple of days to provide a clear status of how much of that makes 1.3.

**Comment by knolleary** [comment]
Delivered in 1.3. The next iteration is a bigger item - #1578 that will supersede the work done here.
