### ISSUE TITLE
Need to track customer journey from first interaction to being a Flowforge customer

### ISSUE THREAD

**Issue by iskerrett** [flowforge/flowforge#1510]
### Description

We need to be able to track how people first interact with Flowforge (ie, Google search, referred from xxx domain, etc.) to they sign-up for Flowforge to being a paying customer. 

### Tasks:
- [x] Configure app.flowforge.com to record PostHog events in the Website Project
- [x] Transfer historical App PostHog project data to the Website project
- [x] Manually recreate the relevant Dashboards & insights in the FlowForge Website project on PostHog
- [x] Include e-mail in PostHog identify call (#1587)
- [ ] Enable and configure the HubSpot <> PostHog Integration App, so HubSpot contacts are auto-created when users sign up.

**Comment by joepavitt** [comment]
We currently use PostHog to track this data, although we have two distinct applications: `www.flowforge.com` and `app.flowforge.com`.

As the user visits and explores our website, we understand well their referral domain and what they explore. This data is lost once they transition to `app.flowforge.com` via our "Join FlowForge Cloud" CTA as at that stage, they enter a new domain, are assigned a new ID, and their referral domain is then `www.flowforge.com`.

Posthog enables us to define our own id's for tracking a "Person" (https://posthog.com/docs/integrate/identifying-users) which we do for users signed into and using FlowForge Cloud. What we need, is a mechanism by which to bridge between the Website ID and the Application ID.

I have asked in the Posthog Slack for any recommended Best Practices here.

**Comment by joepavitt** [comment]
https://posthog.com/docs/how-posthog-works/ingestion-pipeline#merging-two-persons

PostHog detailing a few issues with the idea of "merging", particularly with historical events. So it does mean that we will not be able to get the conversion data for all existing users unfortunately.

**Comment by joepavitt** [comment]
Our approach here now needs to be to merge our "Website" and "App" projects into one, i.e. use the same API key in both deployments.

We will keep the Website API Key, and update the app.flowforge.com API key so that all future raw event data from the app will instead be recorded in our Website project. The reason we are doing it this way is:

 - When doing a PostHog replication (i.e. transferring historical data), we can only move over the raw event and user/person data, we lose Insights and Dashboards, of which we have many more in the Website Project. It will be easier to reproduce the App dashboards manually.
 - We have already mapped FlowForge user ids to the anonymous ids assigned by PostHog in the App project, these will transfer across. This also means that if a registered user signs into FlowForge after this change, the Posthog ID will actually be that of the website, our app will then map their FF id to the Website ID, meaning that we will have two records, but both will have the mapped FF id. If we do it the other way around, the website ID will remain anonymous.
 - PostHog does not currently enable merging of users, but this will at least give us better data should we wish to do so in the future.

**Comment by joepavitt** [comment]
Ben has updated the API key in production, so we now have reporting on app.flowforge.com into the "Website" project.
I have also just kicked off the PostHog replication to transfer over the historical data, but it's a _very slow_ process: https://app.posthog.com/app/19771/historical_exports

**Comment by joepavitt** [comment]
The transition of historical data has gone pretty badly. No data transferred, and the PostHog UI is bugging out a lot, not able to re-run job, or track progress of job without hitting errors. Have reached out to PostHog for support, but not anticipating any updates until next week now.

**Comment by joepavitt** [comment]
FlowForge App data has successfully been transferred into the FlowForge Website project - now just need to manually recreate all of the insights/dashboards that we used in the other project.

**Comment by joepavitt** [comment]
HubSpot integration with PostHog is enabled:

<img width="1446" alt="Screenshot 2023-01-18 at 16 17 19" src="https://user-images.githubusercontent.com/99246719/213231883-6a0f2963-997d-4b31-9cdb-2d897e338e66.png">

I have also opened #1587 which will include the user's email address in our identify call to PostHog so that we can map that to HubSpot correctly.

**Comment by joepavitt** [comment]
Just to update progress here, @iskerrett flagged that any new FF Cloud customers that had previously registered for a Webinar/Event, do need get flagged in HubSpot. 

PostHog identifies them correctly, but HubSpot integration only creates new accounts, and so no communication occurs if the e-mail is already recognised.

@iskerrett how are we differentiating the different types of contacts in HubSpot, is there a flag to say "existing customer" or something like that?

**Comment by joepavitt** [comment]
What is still missing here? We can track the full funnel in PostHog, I believe we still want to be able to tie back the Stripe/spend stuff back to PH too? And ideally have better annotation of contacts in HubSpot?

**Comment by joepavitt** [comment]
Just spoke with @robmarcer - updates here given his work in Node-RED for HubSpot are one final task:

- Loop through all FF customers in Postgres
- Update respective HubSpot Contact with a `is_ff_cloud_customer` tag, or something along those lines.

We could run this on loop, every day/week, etc

We still have PostHog adding contacts into HubSpot when created, do we still want this @iskerrett? I know the gripe was that those contacts created aren't differentiated as FF Cloud customers. If we are running above loop regularly, we could in theory remove the PostHog <> HubSpot integration and create contacts from Node-RED too

**Comment by joepavitt** [comment]
Confirmed - integration is now switched off.
