### ISSUE TITLE
UI Polish for Free Trials

### ISSUE THREAD

**Issue by Pezmc** [flowforge/flowforge#1521]
### Description

We're introducing support for "free trials" in EE FlowForge and FF Cloud as part of #1471.

The free trials are implemented as a coupon for the cost of a project for a month.

We need to design copy and a UI that highlights this trial to users when they create their first time.

The current proposal is to add banner message to 'create project' page if:
- it is within first month of team creation
- no projects yet created

We'll also need to tweak the accept the prices page when creating the first project.

Seeking input from the team /cc @joepavitt and @iskerrett on the best way to go about this both visually and from a easy marketing perspective.

### Epic/Story

#1471

### Tasks:

These are all nice to haves, rather than being required for #1471 to be considered complete.

_Moved into #1471_

**Comment by iskerrett** [comment]
I think there are 3 pages that need to incorporate the free trial:
1) Home page
- I would like to see signing up to FlowForge Cloud to be the main CTA at the top of the page. This would mean moving the 'Install on our own infrastructure' down the page. Ideally the Join FlowForge Cloud becomes '.  We actuall have this in the 'Start Using FlowForge' right now.   
- Rename 'Join FlowForge Cloud' to 'Get Started for Free'
2)Create Page Updates  https://app.flowforge.com/account/create
- Need to add to the top some text. Example: 'The first 30 days of using FlowForge Cloud are free.  We want to make it as easy as possible to experience the FlowForge. You can cancel at anytime during the 30 days with no charge.'
3) Pricing Page
- Add a call out on the premium price. Something like 'First 30 Days are Free'

**Comment by joepavitt** [comment]
> I would like to see signing up to FlowForge Cloud to be the main CTA at the top of the page. This would mean moving the 'Install on our own infrastructure' down the page.

I believe our main KPI is installed instances of FlowForge, i.e. we're currently being measured more ont he installs of FlowForge, than we are users of FlowForge Cloud - am I mistaken @ZJvandeWeg?

**Comment by Pezmc** [comment]
There are **technical** changes to how the free trial will be implemented, we'll now be applying a credit balance for the cost of a small project for one month to customers accounts, full details in https://github.com/flowforge/flowforge/issues/1471#issuecomment-1377568753; the marketing messaging can remain the same, but we should take care in the small print that it's clearly communicated that it's being applied as a credit.

**Comment by knolleary** [comment]
To add to the comment from @Pezmc, this issue was originally raised to cover UI changes in the Forge Platform. The change in approach described in #1471 includes the following two changes on the platform UI:

 - Add the customer's 'credit balance' to the Team Billing Page
 - Add the customer's 'credit balance' to the Create Project page

By doing this (in particular, the second one), it will help inform the user that they have credit available in their account. This greatly simplifies the UI changes needed (to keep this containing in 1.3).

**Comment by Pezmc** [comment]
@joepavitt Here's a rough overview of how the free trial currently looks to the user, we should use these screenshots to decide what further UI and UX changes should be made in Forge Platform UI to make it clearer what is happening:

### Creating a new team

Currently no mention that they're going to be getting a trial.

<img width="1243" alt="Screenshot 2023-01-10 at 18 17 53" src="https://user-images.githubusercontent.com/507155/211619295-22c7f0b4-ab8f-4cfc-b56c-802a04fcd893.png">

### Adding details on stripe

No mention of the trial and there's VERY little we can change about this page, other than the tiny text just above the subscribe button and the product description of the team plan.

<img width="1188" alt="Screenshot 2023-01-10 at 18 18 38" src="https://user-images.githubusercontent.com/507155/211619300-75ce97cd-d7c7-4e7e-be1d-b2c780e047fe.png">

### Landing page after signing up

We've discussed changing this to take you straight to the create project page

<img width="1192" alt="Screenshot 2023-01-10 at 18 18 52" src="https://user-images.githubusercontent.com/507155/211619301-1a8339a6-b36d-4565-82c1-14db04cffe20.png">

### Creating a new project

Proof of concept banner has been added here showing that there is credit that will be (partially) used.

<img width="1199" alt="Screenshot 2023-01-10 at 18 19 04" src="https://user-images.githubusercontent.com/507155/211619308-8522cc86-4ef7-4850-8bc5-15e0357906be.png">

### Landing page after creating the new project

Back to no mention of the credit

<img width="1332" alt="Screenshot 2023-01-10 at 18 24 00" src="https://user-images.githubusercontent.com/507155/211620010-262d5c0d-901e-42eb-b30c-783b18fba378.png">

### Visiting the Team Billing page while there is credit

Proof of concept addition of showing the credit balance

<img width="1192" alt="Screenshot 2023-01-10 at 18 18 57" src="https://user-images.githubusercontent.com/507155/211619305-fdbf906f-820f-4c30-92a5-94bb7431c238.png">

### The customers stripe billing page

Of note:
 - Zero mention of any credit balance at any time
 - The customer will start with two $0 invoices, one from the free team plan, and one from the creation of a project, which used their credit.
 - An additional $0 invoice will be created if the project is cancelled/suspended, which moves refunds the credit balance back to the customer.

<img width="1141" alt="Screenshot 2023-01-10 at 18 25 26" src="https://user-images.githubusercontent.com/507155/211620289-0721190d-84f7-4edb-ae7a-819f7f5244e1.png">

**Comment by joepavitt** [comment]
> Landing page after signing up
We've discussed changing this to take you straight to the create project page

I understand why we would want to encourage this, particularly in the case of a trial, but I think I'd like to keep it as is for now. Personally, I like being given a chance to explore UI, rather than being forced down a rabbit hole.

**Comment by joepavitt** [comment]
> Adding details on stripe
> No mention of the trial and there's VERY little we can change about this page, other than the tiny text just above the subscribe button and the product description of the team plan.

Can we change the text to something along the following lines:

Text above Subscribe:
```
This sets up your team for billing. You are only charged when creating a Project.
```

then, for ht description, the above text, with the additional sentence:
```
For the first month of using FlowForge, you will be given credit for 1 x Small Project for free.
```

**Comment by joepavitt** [comment]
> Creating a new project
Proof of concept banner has been added here showing that there is credit that will be (partially) used.

May I propose the following: 

<img width="1793" alt="Screenshot 2023-01-11 at 16 51 21" src="https://user-images.githubusercontent.com/99246719/211867091-b879162a-9b59-474f-a867-845b69dd0c64.png">

- New "Charges" section on the right to show breakdown of cost & any credit.
- Explicit mention of the total cost in the "Additional Charges" confirmation description

**Comment by joepavitt** [comment]
> Landing page after creating the new project
Back to no mention of the credit

Um'ing and arr'ing about this screen. Do we have context that the current month they're on is funded by credit? If so, we could utilise our message banner to display how many days left until they're charged.

If we don't have that context, I'm not sure we want to, or even can, do much here?

**Comment by knolleary** [comment]
> For the first month of using FlowForge, you will be given credit for 1 x Small Project for free.

The credit has no time limit on it. The value is equivalent to 1x Small Project running for a month - I think we want to be careful with how it is described so we don't cause confusion.

I also think it would be important to mention *why* they have got this credit, because when them come to create their next team, they won't get it. How about:

> As this is your first FlowForge team, we’re giving you free credit equivalent to a Small Project for one month’. This will be applied to your next Stripe invoice.

---

I'm not sure your proposed Charges section works for me. There is only ever going to be a single charge - this UI implies they could have multiple charges racking up in the single action. And there will only ever be a credit line the first time they create a project. From then on, it will only ever be a table with one entry and a 'total' matching that one entry. Doesn't feel quite the right use of the space to me.

If anything, that could move down to where the existing 'confirm additional charges' checkbox is - do something in that space to summarise the charge and what credit they have.

**Comment by joepavitt** [comment]
> I'm not sure your proposed Charges section works for me.

All very valid, alternative: 

<img width="1601" alt="Screenshot 2023-01-11 at 17 10 04" src="https://user-images.githubusercontent.com/99246719/211871335-963eab94-d54c-4514-ae69-9ee7aaafb4e9.png">

**Comment by joepavitt** [comment]
> I also think it would be important to mention why they have got this credit, because when them come to create their next team, they won't get it. How about:
> 
> > As this is your first FlowForge team, we’re giving you free credit equivalent to a Small Project for one month’. This will be applied to your next Stripe invoice.

Agreed, much better, although did make me think, are we able to set that message in just the instance where it is their first team, and when credit is still available? Otherwise, we do not want to show that.

**Comment by Pezmc** [comment]
> Can we change the text to something along the following lines:

Yes, but the Team Product description is set across all checkout sessions, even teams not being offered a free trial (as per your comment above). However I've found a possible workaround by having two team products in stripe, one for free trialers, one for normals.

Action points from the comments above:

- [ ] Text above Subscribe on Stripe Checkout 
    > This sets up your team for billing. You are only charged when creating a Project.
- [ ] Stripe Checkout Team Product Description - Needs technical investigation (create two team products?)
    > As this is your first FlowForge team, we’re giving you free credit equivalent to a Small Project for one month’. This will be applied to your next Stripe invoice.
- [ ] Charges Section on Create Project Page
- [ ] More subtle credit balance banner on Create Project Page

**Comment by joepavitt** [comment]
> However I've found a possible workaround by having two team products in stripe, one for free trialers, one for normals.

wouldn't that mean users would have to switch products after their "trail" expires, feels dirty, and for the sake of that message (which we'll improve communication of elsewhere anyway), we should stick with the one team subscription.

**Comment by Pezmc** [comment]
I'm marking this as complete and tracking any leftover follow ups in #1471 so they're in one place.
