### ISSUE TITLE
Introduce Application model to runtime

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#1735]
### This Issue
This issue tracks *backend changes*, and front-end changes required to be inline with the latest backend.

UI only changes are being tracked in #1689.

### Description

Want to break this into a standalone task to track discussion and. final decision going forward as this is relevant for https://github.com/flowforge/flowforge/issues/1689

@ZJvandeWeg had proposed that we rename "Project" > "Application". My own thoughts are that I'm not against this, I understand the incentive behind it, and it would make the migration from Project > Application/Instance split easier than if we split Project > Project/Instance, where the new Project has a different meaning/scope to the original.

<img width="1159" alt="Screenshot 2023-02-13 at 20 00 52" src="https://user-images.githubusercontent.com/99246719/218562383-b720012e-e146-4e01-8bb1-db5b4940fc0c.png">

Diagram taken from: https://github.com/flowforge/flowforge/issues/1450#issuecomment-1428596043

### Epic/Story

#1450

Plan of action:

```[tasklist]
- [x] Introduce `Application` db model - this is a parent container of multiple `Projects`.
        `id` - use hashid like other things
        `name` - free form, no constraints
- [x] Create CRUD endpoints for working with Application
- [x] Application API end point to list Application instances (via #1813)
- [x] Create Migration to generate Application object for all existing Project objects (via #1813)
- [ ] https://github.com/flowforge/flowforge/issues/1863
- [ ] https://github.com/flowforge/flowforge/issues/1867
- [ ] https://github.com/flowforge/flowforge/issues/1868
- [x] Delete Instance - update UI to just delete instance, not application as well
- [ ] https://github.com/flowforge/flowforge/issues/1870
- [x] Delete Application - update UI to use Application endpoint for deleting
- [x] Team API end point to list Application instances
- [x] Renaming of Applications
- [x] Update top-level instances view (#1852) to use Team/Instance API
- [ ] https://github.com/flowforge/flowforge/issues/1911
- [ ] ----- review ------
- [x] Support changing Application name (API/Frontend)
```

**Comment by knolleary** [comment]
Following a discussion around the backend changes needed for #1689, we have agreed, in the db model, to introduce a new `Application` object that sits about what we currently called `Projects`. This will allow us to introduce this collection object without forcing us to changing the meaning of Project throughout the code base at the same time.

Plan of action:

```[tasklist]
 - [ ] Introduce `Application` db model - this is a parent container of multiple `Projects`.
        `id` - use hashid like other things
        `name` - free form, no constraints
 - [ ] Create CRUD endpoints for working with Application
 - [ ] Update 'Create Project' endpoint to require an Application ID - needs to be done in co-ordination with frontend
```

The work around renaming Projects to Instances is covered by #1720

**Comment by knolleary** [comment]
I'm assigning this task to @pez as he has the initial task of introducing the Application model to the database - as described in the tasklist I've added.

**Comment by knolleary** [comment]
An aspect we haven't covered in our discussions so far is what migrations are needed for existing FF instances.

We need to create an Application object for each existing Project and establish the relations properly between them. We should use the name of the project as the name of the application.

**Comment by ZJvandeWeg** [comment]
@knolleary is it possible to alias a table name in the ORM? So the code changes, everything seems an application, but the table name is projects?

**Comment by knolleary** [comment]
@ZJvandeWeg I think it is possible and will be something we look at as part of #1720 which is the task related to the underlying db changes around the Project object becoming an Instance object.

To clarify:
 - for the end users what we currently call Projects will become Applications.
 - in the underlying DB model, the model we currently call Project will become an Instance (because in the model, Project has far more in common to what we want Instance to be than it does what the Application will be). That work is covered by #1720

**Comment by joepavitt** [comment]
Final decision has been confirmed to change Project > Application

**Comment by Pezmc** [comment]
Work in progress branch of server side changes is at: https://github.com/flowforge/flowforge/compare/feat-1735-application-model

**Comment by Pezmc** [comment]
All follow up tasks have been moved to #1914, considering this complete.
