### ISSUE TITLE
Onboarding FlowForge to AWS Marketplace (container-based product)

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#1942]
### Description

By providing FlowForge via AWS Marketplace, we are streamlining the process for customers to use and deploy FlowForge on AWS effortlessly. AWS Marketplace simplifies the billing process for our customers, as they can manage their FlowForge license through their existing AWS accounts. This streamlines their billing experience.

AWS Marketplace has a vast user base, providing increased visibility and reach for our offering. By listing our product on the platform, we can attract more customers and expand our market presence.

## Tasks

```[tasklist]
### Implementation
- [ ] Ensure Compliance with [AWS Container-based product requirements](https://docs.aws.amazon.com/marketplace/latest/userguide/container-product-policies.html)
- [ ] [Integrate AWS license manager](https://docs.aws.amazon.com/marketplace/latest/userguide/container-anywhere-license-manager-integration.html)
```
```[tasklist]
### Organizational
- [ ] End User License Agreement (EULA) URL – Your product must have a EULA, and you must provide a link to it for customers to read and review on your product's AWS Marketplace page.
- [ ] Creation of AWS offering page (Product title, describtion, logo, highlights etc.)
```
### Notes

- First step, could be BYOL

**Comment by hardillb** [comment]
Container based app requirements

- [ ] No CVEs on the containers, 1.9 containers all clean (bar the 2.2.3 Stack container)
- [ ] Need to add random initial password (#2443)
- [ ] Review AWS T&Cs



[AWS Marketplace Seller Terms and Conditions.pdf](https://github.com/flowforge/flowforge/files/12002002/AWS.Marketplace.Seller.Terms.and.Conditions.pdf)

**Comment by hardillb** [comment]
- [ ] work out how to configure

**Comment by hardillb** [comment]
- [ ] We will need a link to the EULA for the Container applicaiton

**Comment by hardillb** [comment]
Having spent most of the week trying to work out how to make this work I am struggling.

- I don't think we can use the current Docker Compose version as it requires the configuration file to be built from a template then mounted into the container. AWS CloudFormation doesn't appear to be able to do this
- We might be able to use the kubernetes version, but it appears to require setting up the full EKS cluster as a CloudFormation template, which requires huge amounts of knowledge about different components (VPC, EC2 Images, Security Policies,.....) then chaining in building a template to setup the RDS database and probably SES email, before finally doing the helm install.

I'm struggling to find any example templates for the EKS that are up to date or not abandoned.

We may be able to build a new container for the Docker driver that can be configured purely from environment variables as a solution to first option.

**Comment by hardillb** [comment]
Build as a VM image product (so even closer to Digital Ocean Droplet) using packer.

**Comment by hardillb** [comment]
https://github.com/flowforge/aws-ami

**Comment by MarianRaphael** [comment]
https://aws.amazon.com/marketplace/pp/prodview-3ycrknfg67rug?sr=0-1&ref_=beagle&applicationId=AWSMPContessa
