### ISSUE TITLE
Provide persistent context options

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#212]
### Description

The default Context storage in Node-RED is memory only.

A value-added feature is to support persistent context storage options - such as via Redis.

A possible extension would be to support sharing the context store between two projects in the same team - useful for high-availability type scenarios.

### Which customers would this be availble to

- [ ] All Users, (CE)
- [X] Specific Project Types (EE)
- [ ] Specific Team Tiers (EE)
- [ ] Other (See comments)

**Comment by sammachin** [comment]
Initial user feedback is showing strong support for this feature

**Comment by sammachin** [comment]
What should happen to persistent context data when a project is suspended, should we clear the data or not?

**Comment by knolleary** [comment]
There are three key design points for this item:

 1. what backend storage mechanism is used
 2. how this storage layer handles authentication
 3. how this applies to Devices-vs-Projects

We added the File Server component to the platform in 1.1.0. This already solves the authentication question and I propose we extended it to also provide a Context API. That solves item 2.

For item 3, Devices should be configured with a standard built-in file based context - they do not need to access the File Server.

That leaves Item 1 - what backend storage we use for context requests. When running locally, it can still be a local file based implementation. When running in the cloud, I don't think it make sense to leverage the S3 api - S3 isn't really suitable for the sort of traffic context could generate and would get expensive. Redis has long been the assumed best service for Context - what options are available for the k8s and docker deployments?

**Comment by Steve-Mcl** [comment]
> When running in the cloud, I don't think it make sense to leverage the S3 api - S3 isn't really suitable for the sort of traffic context could generate and would get expensive

What if (similar to the NR file backed context) we use a memory cache & flush every 30? Is that still too frequent?

**Comment by knolleary** [comment]
> What if (similar to the NR file backed context) we use a memory cache & flush every 30? Is that still too frequent?

It depends on what quality of service we want to provide. Having a potential 30s data loss window could be a problem.

But equally, for an initial iteration, it could be okay if it removes the need to introduce another data service. Before we commit to a path however, we should understand the $ costs of S3 - it isn't really intended for this type of usage so its pricing could well penalise us quite heavily.

We can make a start on all the other bits whilst we validate the choice of service.

**Comment by Steve-Mcl** [comment]
_(thinking out loud / definitely lateral / one for discussion?...)_ 

I wonder if we could utilise persistent MQTT topics in the (existing) broker as the cache & flush less frequently? 
Any project crash would then not result in cache loss. (though broker crash would lose cache). 🤔 

NB: Will be speaking with Ben very shortly (slack huddle) about this epic.

**Comment by hardillb** [comment]
MQTT brokers should not be used as ad-hoc object stores

Current consideration is to build something very similar to the file-server, but using Redis (or similar) as the backend

**Comment by hardillb** [comment]
Will look at the 2 different AWS services that provide Redis support https://aws.amazon.com/redis/

- MemoryDB
- ElasticCache

Also need to have another look for Postgres HStore client for NodeJS, all the ones I've found so far are abandonded.

After talking to Nick, I will add some more endpoints to the file-server rather than start another new project

**Comment by Steve-Mcl** [comment]
- [ ] Ben: first pass at API (in file-server) with basic mem backend
- [ ] Steve: Other priority tasks (NR 3.1 related) (28th / 29th morning)
- [ ] Ben: Push to private repo (29th Nov afternoon)
- [ ] Steve: Pull & 1st implementation of NR context plugin to utilise (29th Noon / 30th Morning)

#### Items to clarify and plan out.
* project settings (enable/disable)
* naming
  * device agent should have matching store which is original (actual) file store
  * design decision on when to delete that store (potentially when project ID changes)
* will it be default context?
* quota considerations
  * mem + storage
* improve logging for capturing use/overuse
* TBD production backend(s) TBD over coming days. (evaluation & discovery ongoing)

**Comment by hardillb** [comment]
First pass at context api

https://github.com/flowforge/flowforge-file-server/tree/persistence-context

**Comment by ZJvandeWeg** [comment]
> project settings (enable/disable)

@Steve-Mcl  I'd rather not have more options. Either this improves something and it's enabled by default, or we don't build the feature at all.

**Comment by Steve-Mcl** [comment]
> > project settings (enable/disable)
> 
> @Steve-Mcl I'd rather not have more options. Either this improves something and it's the only way forward, or we don't build the feature at all.

ZJ, This is referring to how we enable / disable the context plugin automatically due to env (e.g. cloud vs device) - not a user option.

The above points were only ever intended to be be reminders for myself and @hardillb to come back and pad these out with details once the initial "first pass" was done.  Will try to be more explicit in future.

**Comment by Steve-Mcl** [comment]
29/11/2022
- [x] Ben: first pass at API (in file-server) with basic mem backend
- [x] Steve: Other priority tasks (NR 3.1 related) (28th / 29th morning)
- [x] Ben: Push to private repo (29th Nov afternoon)
- [x] Steve: Pull & 1st implementation of NR context plugin to utilise (29th Noon / 30th Morning)

## meeting 5/12/2022
* [x] Ben to implement `clean` API at backend
* [x] Default name for this store to be `persistent`
   * [x] Additionally, the memory store should be named `memory` and be set as default
* [x] ship minimal version on staging by Wednesday 7th
    * [ ] Document any limitations or temporary workarounds along with 1st push
    * [ ] Follow up meeting to discuss the feedback and direction
* [ ] Following 1st release practical tests on staging, address the issue of whether to implement a cache to support  `sync` functions
* [ ] PR device agent to have 2 default context stores `persistent` & `memory` (to match cloud project)


#### Items to clarify and plan out.
* ~~project settings (enable/disable)~~
* ~~naming~~
  * ~~device agent should have matching store which is original (actual) file store~~
* design decision on when to delete that store (potentially when project ID changes)
* ~~will it be default context?~@ No
* quota considerations
  * mem + storage
* improve logging for capturing use/overuse
* TBD production backend(s) TBD over coming days. (evaluation & discovery ongoing)
  * Currently, (for testing) a memory and Redis backend have been implemented. 
  * Use of the existing FF database to be considered before decision is made.

**Comment by knolleary** [comment]
As this issue is in the Done column on the dev board and was delivered in 1.2 can it be closed? Any follow-on items should be raised as separate issues at this point.

**Comment by Steve-Mcl** [comment]
Yes, I believe now is ok - we have raised an issue for the timeout problem and working s3 tests are in a PR (I am currently testing the minio stuff locally)
