### ISSUE TITLE
Phase 1: Split Between Starter and Premium Tiers

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2328]
### Description

Phase 1 of this transformation concerns the creation of a "Starter" tier, which we aim to make more of a package than a tier. This new package would allow for 2 Node-RED instances, 2 Devices and 2 team members for a fixed price per month. While SLA’s won’t be provided for the service or support, support will be done through a public forum. 

Packaging details: [Google Docs](https://docs.google.com/document/d/1dfFwM5_V_5928Fm2kxhOOnGOFJsiZUUyzN48z9mp2NQ/edit?usp=sharing)

```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/2282
- [ ] https://github.com/flowforge/flowforge/issues/2359
- [ ] https://github.com/flowforge/flowforge/issues/2360
```

**Comment by joepavitt** [comment]
Key focal point for design phase here is what the upgrading path looks like - how do we limit resourcing, but advertising next package options?

**Comment by MarianRaphael** [comment]
Yes, exactly. Key UX paths are:

- What should the information page look like, either directly before or after providing payment information?
- How should we display the limits of the starter package?
- What should the user journey look like when upgrading to Premium?

**Comment by joepavitt** [comment]
First pass at a new "Billing" view for those on the "Starter" tier. Will be designing a variation of this for "Premium" and working on an "Upgrading to Premium" workflow/screen:

<img width="1341" alt="Screenshot 2023-06-29 at 11 47 48" src="https://github.com/flowforge/flowforge/assets/99246719/3a9c221e-af93-4cba-a1c3-1fbe59ad2f1b">

**Comment by joepavitt** [comment]
Thoughts on how we show the "comparison" as they're going through upgrade, to be explicit about what changes there are to plans, and what they're getting for their money.

<img width="1466" alt="Screenshot 2023-06-29 at 12 33 34" src="https://github.com/flowforge/flowforge/assets/99246719/7e9dfdbe-e85e-48a2-bc47-ec98a25761aa">

**Comment by joepavitt** [comment]
Couple of variants for the "Premium" Equivalent which requires a deeper breakdown of costs and items (as now paying per instance). The technical challenge here is how do we build something that is friendly on both starter/premium, but without compromising hard-coded statements that are _just_ built to our own billing model on FF Cloud, and dismisses the FF self-hosted option.

<img width="1506" alt="Screenshot 2023-06-29 at 16 57 56" src="https://github.com/flowforge/flowforge/assets/99246719/fbf29408-a9ef-4321-b02c-8249c75fd233">

<img width="1496" alt="Screenshot 2023-06-29 at 16 58 01" src="https://github.com/flowforge/flowforge/assets/99246719/eae93b46-e06d-44cf-8fe7-db9de1e4131f">

**Comment by joepavitt** [comment]
The annoying challenge here is that the number of instances/devices can be split across Applications. The Instances list view is bound to an Application. So we're not sure if they're breaching limit without additional API calls to _other_ applications.

**Comment by joepavitt** [comment]
On the Instances view, we could mimic the style introduced [here](https://github.com/flowforge/flowforge/pull/2290#issuecomment-1609150853)

<img width="1918" alt="Screenshot 2023-06-30 at 13 57 57" src="https://github.com/flowforge/flowforge/assets/99246719/dff545c4-e9db-4c37-ba83-16f7072f1635">

Challenge is a configuration/definition of that message, and the rules for display. Easy solution is as we've done the existing checks for Trials, but here it's a little more complex, as would also have consequences for messages being shown to _all_ FlowForge instances. In this case though, I think that's okay? How does OS get affected by this new packaging? Is that still free for all, or are we introducing caps there too @MarianRaphael?

**Comment by MarianRaphael** [comment]
@joepavitt in this iteration, the open-source functionality remains unchanged. In the Google Docs file, you can see both variants: FF Cloud and Self-Hosted. As a result of the issues here, we end up with two tiers for FF-Cloud (Starter/Premium) and two tiers for Self-Hosted environments (OS/Premium).

**Comment by MarianRaphael** [comment]
> Option B: Tried to group accordingly with the instances, and a broken down statement of sizing.

I like Option B more, it looks cleaner and more structured to me.

**Comment by iskerrett** [comment]
Will we still have a Free Trial for the Starter package? If yes, we might want to also consider what is the upgrade UX from free trial to paid package.

**Comment by MarianRaphael** [comment]
@iskerrett Yes see https://github.com/flowforge/flowforge/issues/2282
@joepavitt could you pick this up, or would it basically be like this here:https://github.com/flowforge/flowforge/issues/2328#issuecomment-1612963139

**Comment by joepavitt** [comment]
Not sure we (for now/1.10) need tk venture too far away from the UX of existing trial users which shows a consistent banner across the top of the platform indicating time left on trial, that they need to setup billing to keep instances beyond 30 days, etc

**Comment by joepavitt** [comment]
Although, actually I guess now the decision isn't just _I want to pay for FF Cloud_ it's _I want to pay for FF Cloud, and need to choose which tier_?

**Comment by joepavitt** [comment]
Quick thoughts based on https://github.com/flowforge/flowforge/issues/2328#issuecomment-1612963139 (note the empty state graphic will be updated to reflect the page, just put that in as a placeholder)

### Figma Prototype

https://www.figma.com/proto/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?page-id=0%3A1&type=design&node-id=2493-18259&viewport=-7845%2C-5052%2C0.74&scaling=min-zoom&starting-point-node-id=2493%3A18259&show-proto-sidebar=1&mode=design&t=DhF8dJvDse2TG530-1

### Static Screenshots:

<img width="1705" alt="Screenshot 2023-07-06 at 18 13 55" src="https://github.com/flowforge/flowforge/assets/99246719/6937f37f-5cd2-487f-9b85-c80684fb545f">

<img width="1682" alt="Screenshot 2023-07-06 at 18 14 01" src="https://github.com/flowforge/flowforge/assets/99246719/e1d382fc-56c1-45d5-9f6d-94b02f3954a1">

**Comment by knolleary** [comment]
On Upgrade path UX - depending on how we migrate existing users, one option is to let them 'upgrade' themselves from the old style starter to one of the new tiers (see my comments on #2360 for which I think this part of the approach we should take).

However it is possible they are already exceeding the limits of the new Starter tier - so the upgrade UX needs to cater for this and not allow someone to 'upgrade' to a tier that is smaller than their current usage.
