### ISSUE TITLE
Device UX Review

### ISSUE THREAD

**Issue by joepavitt** [flowforge/flowforge#2427]
### Description

Having just done a [UX Review on Devices](https://www.figma.com/file/JlbuwrGYgxYOV3DKlLck9J/User-Journeys---Devices?type=whiteboard&node-id=0%3A1&t=KCBhnqf2CBCl5yk3-1) I've flagged multiple areas of frustration and ideas for improvement that I'll be documenting here:

### Setup Phase - Adding a Device
![image](https://github.com/flowforge/flowforge/assets/99246719/8ce34984-d366-40a6-8123-0a29357e4276)

```[tasklist]
- [ ] Not clear what "type" is when adding a device
- [ ] If we stick with Instance binding to a device, then we could have an option here to 
- [ ] "type" here should be a combobox (dropdown with text input)
``` 

### Setup Phase - Download YML
![image](https://github.com/flowforge/flowforge/assets/99246719/af64a9fb-fe92-4ceb-bb59-27f7ac905c72)

```[tasklist]
- [ ] Very easy to just click "done" and miss the "make note" comment in the description
- [ ] Little clarity here in the messaging on what to do with the `device.yml` - even when downloaded
``` 

### Setup Phase - Binding Device to Instance

This entire step feels very unintuitive. #2334 seeks to move the Devices to nest below Applications, rather than Instances, which would have some level of impact here as currently, to deploy a set of flows to a Device, you need to go via a Snapshot on an Instance first.

![image](https://github.com/flowforge/flowforge/assets/99246719/66ec7689-bf43-42e0-9ed0-8a98bbad1f19)

```[tasklist]
- [ ] Add option to bind Instance on the "Device" screen, rather than the kebab menu
- [ ] On the modal "Add Device to Instance" show the Target Snapshot that will be pushed to the device, if set.
``` 

### Action Phase - Setting Target Snapshot

![image](https://github.com/flowforge/flowforge/assets/99246719/66ec7689-bf43-42e0-9ed0-8a98bbad1f19)

```[tasklist]
- [ ] No "Target Snapshot" define on "Instance > Snapshot" page
- [ ] Creating a snapshot, feels a little empty, no context as to content of flows/snapshot.
- [ ] Not obvious you can click "Application" and "Instance" in the Devices table
```

**Comment by GogoVega** [comment]
To filter devices, "type" is used but that doesn't give many options to filtering. Would adding a "room" option be useful?

I think I saw a request (yeah #723) to show a list of existing types, perfect.

I understand the reason for the "Last Known Status" (devices page) but visually I am missing a "Not Responding" flag which would allow me to filter these devices (?)

The device page where "Status" is listed is not correct, it is either "Last Know Status" or use the "Not Responding" flag.

**Comment by joepavitt** [comment]
> I am missing a "Not Responding" flag which would allow me to filter these devices (?)

You can click on the charts at the top of the Devices page, which show the last connected time, and you could filter to device last connected over 3 minutes ago (for example)
