### ISSUE TITLE
Adding a Catalogue.json URL and npm repository (Settings)

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2526]
### Epic

https://github.com/flowforge/flowforge/issues/217

#### Story 1

As a FlowForge Team Owner,
I want to be able to add a "catalogue.json URL" to a specific Node-RED instance via FlowForge settings,
So that my Node-RED instances can have access to additional npm custom modules.

#### Story 2

As a FlowForge Team Owner,
I would like to add an alternate npm repositories via FlowForge settings,
So that my Node-RED instances can have access to additional npm custom modules.

### Which customers would this be availble to

Licensed Edition (EE)
Teams Tier

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] Adding a "catalogue.json URL" to a specific Node-RED instance
- [ ] Documentation: How to generate a catalogue.json
- [ ] Ability to configure alternate npm repositories (e.g. modfify .npmrc file)
- [ ] Device compatibility
- [ ] Add Feature Flag to ensure this is enabled for Teams team type and not starter
```

**Comment by hardillb** [comment]
This will probably also require the ability to configure alternate npm repositories as a custom catalogue is likely to include nodes not available in the public repository.

**Comment by hardillb** [comment]
- This work will need to apply to the device agent as well as the cloud instances.
- Need to decide if we make private npm repos scoped or not (this will depend on if the repo supports "pass through"
- private npm repos will also optionally need a security token/password to access

**Comment by hardillb** [comment]
Design question: 1 or more catalogue options? Like wise with registries

**Comment by hardillb** [comment]
This will need to be gated on the latest version of the nr-launcher (and device agent)

**Comment by MarianRaphael** [comment]
Should we allow more than one catalogue? Yes 
Should we allow the default catalogue to be removed? Yes
(From Slack)

**Comment by hardillb** [comment]
verified on staging
