### ISSUE TITLE
TeamTypes: enable feature flag constraints

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#2531]
### Description

Part of #2359 

The new TeamType objects include a `features` object in their properties to contain any flags/constraints that should be applied to individual features on the platform.

Those constraints are not currently applied - and need to be before we can launch the new tiers in FF Cloud.

With #2519 merged, the TeamType can have the following properties set via the UI. The names have been chosen (where applicable) to be consistent with the corresponding platform feature flag.

 - `properties.features.projectComms` : Project Nodes (boolean)
 - `properties.features.shared-library` : Team Library (boolean)
 - `properties.features.teamHttpSecurity` : Team-based Endpoint Security (boolean)
 - `properties.features.ha` : High Availability (boolean)
 - `properties.features.fileStorageLimit` : Persistent File storage limit (Mb - string)
 - `properties.features.contextLimit` : Persistent Context storage limit (Mb - string)

For each of these, we need to introduce the appropriate checks in both frontend and backed to apply them.

In the frontend, any view that has `this.team` should be able to check these flags directly via `this.team.type.properties.features?.ha` (for eg).

For some, such as the Team Library, we have UX in place that tells the user if the feature is not available based on the platform-wide feature flag and invites them to buy a license - linking to our docs. That will need updating to handle the case where the feature is available on the platform, but not for the team - with appropriately updating text and links for what the user can do to upgrade their team (a path we don't have yet...)

The work done in #2519 added a bunch of instance functions to the `Team` model to check its properties (which indirectly refers to its TeamType). I suggest a `getFeatureSetting` function is added (this doesn't have to be in the `ee` code, can be on the base `Team` model) - that provides a convenient way to lookup any of the settings.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [x] Add accessor function for TeamType feature flags
- [ ] https://github.com/flowforge/flowforge/pull/2601
- [ ] https://github.com/flowforge/flowforge-nr-launcher/pull/157
- [ ] https://github.com/flowforge/flowforge/pull/2599
- [ ] https://github.com/flowforge/flowforge-nr-launcher/pull/156
- [ ] https://github.com/flowforge/flowforge/pull/2611
- [ ] https://github.com/flowforge/flowforge/pull/2604
- [ ] https://github.com/flowforge/flowforge-file-server/issues/66
- [ ] https://github.com/flowforge/flowforge/pull/2671
- [ ] https://github.com/flowforge/flowforge/pull/2672
- [ ] https://github.com/flowforge/flowforge-file-server/pull/70
```

**Comment by knolleary** [comment]
All tasks complete and merged to main
