### ISSUE TITLE
Snapshot Management for Devices at Application Level

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2609]
## Description

As soon as Devices can be assigned to applications (without being linked to an Instance). The follow-up question is where to manage and "store" the created Snapshots:

### Snapshots at Device Level:

Since Snapshots are currently managed at the Instance Level, the list of snapshots created for each device should be available only for that specific device at Device level. To promote snapshots to other devices, DevOps Pipelines would need to be extended as a subsequent step.

**Not in scope:**
Snapshots at Application level:

See discussion here: https://github.com/flowforge/flowforge/issues/2335

### Tasks

- [ ] Implementation of a snapshot overview tab for Devices, analogous to Instances.
- [ ] Re-use table `ProjectSnapshots` for snapshot storage, but will require a new column to identify `ownerType`. At this iteration, that will be `null`, "device" or "instance". `projectId` field will be re-used for "device ID".  If possible/viable, rename field to `ownerId`.
- [ ] When a Device is unassigned from an Application and reassigned to an Instance, either a warning that the snapshots will be deleted should exist, or (better) the possibility to merge the snapshots in the instance list should be available.
- [ ] Possibility to create snapshots for a standalone device.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
## Q1
> Implementation of a snapshot overview tab for Devices, analogous to Instances.

Would we expect to see the "Snapshots" tab when a device is bound to an instance too? In exploring the design today, it doesnt really fit.  For example, following the [figma](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?type=design&node-id=2609-19957&mode=design&t=cTrJVI28CXdtZxLw-0), I currently have this: 


![Image](https://github.com/flowforge/flowforge/assets/44235289/4202f0ab-8274-41c3-92b6-a4bf9932982d)


<br>

## Q2

> Possibility to create snapshots for a standalone device.

When an instance has no snapshots, the empystate permits snapshot creation. 


![Image](https://github.com/flowforge/flowforge/assets/44235289/9cebbf00-5571-47d5-8ccf-9407c45dab6f)


However, currently, a device needs to be in developer mode to create a snaphot and that is done from the developer section on the overview:


![Image](https://github.com/flowforge/flowforge/assets/44235289/fff4d156-6fc9-4174-b308-c8d04cb1f919)


And lastly, the figma drawings show snapshot creation under a new **Developer Mode** tab:

![Image](https://github.com/flowforge/flowforge/assets/44235289/d8a064d6-74e1-48ec-b42b-ff4c7ce217a8)



How should I reconcile this? What is the immediate conclusion/iteration please?

**Comment by joepavitt** [comment]
Will address all of this tomorrow from a UX perspective

**Comment by joepavitt** [comment]
Realise [this comment](https://github.com/flowforge/flowforge/issues/2484#issuecomment-1706456795) would have been better served here, but just linking for reference.

**Comment by Steve-Mcl** [comment]
FAO @knolleary @MarianRaphael 

There is currently no concept of audit log at application level.  Much of the snapshotting and its related audit logs are directed to the project scope auditing.

It may well be out of scope for this particular task, but it is something that will be need to be assessed / implemented.  Should there be a task or new story around this?


Thoughts please?

**Comment by knolleary** [comment]
> Should there be a task or new story around this?

Yes please - it is a new task that should be raised and tracked separately.

**Comment by joepavitt** [comment]
It's already been rasied: https://github.com/flowforge/flowforge/issues/1978

**Comment by Steve-Mcl** [comment]
Verified on staging

https://github.com/flowforge/flowforge/assets/44235289/91b5c887-f8bf-4dd5-a55d-64cdd70e54e0
