### ISSUE TITLE
Push Snapshots Through DevOps Pipeline

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2651]
### Description

**As a:** FlowFuse User who works with Snapshots

**I want to:** have the possibility to push Snapshots through a DevOps Pipeline, "replacing" the current Instance Status method

**So that:** my Snapshots become the single point of truth for my implementations, making it easier to manage deployments, rollbacks, and configurations.

See also: https://github.com/flowforge/flowforge/issues/2600

### Which customers would this be availble to

Licensed Edition (EE)

### Acceptance Criteria

- [x] allow users to select Snapshots as the deployable unit in the DevOps pipeline
- [x] the Snapshot should be visible in the new Instance Snapshot Overview page with the same name (or v2, v3 ...)
- [ ] the current target snapshot should be the default snapshot selected

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [x] Add 'action' field to PipelineStage model (migration etc)
- [x] Allow action to be configured in UI
- [x] Create 'use latest snapshot' action type
- [x] Create 'prompt to select snapshot' action type
```

**Comment by knolleary** [comment]
Proposal via a quick mock-up:

 - Add an 'action' field to the Pipeline Stage. This lets the user pick what the stage should do when triggered.
 - Options:
    - 'Create new snapshot' - existing behaviour
    - 'Use latest instance snapshot' - grabs the most recent snapshot on the instance
    - 'Prompt to select snapshot' - when triggered, show a dialog to pick a snapshot from.

![Image](https://github.com/flowforge/flowforge/assets/51083/bca981a4-4611-4b9d-b8a1-2c86a5d766ee)
