### ISSUE TITLE
Introduce a second Self-Hosted Licensed Tier

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge#2652]
## Description

Currently, we offer two self-hosted tiers for our product: the Open Source (Starter) edition and the Licensed edition. The goal of this feature request is to introduce a third tier. This third tier would split the current licensed edition into two separate offerings: FlowFuse Premium (or Teams) and FlowFuse Enterprise.

The features that will be exclusive to the FlowFuse Enterprise tier are:

- Single Sign-On (SSO)
- High Availability (HA)

### Expected Outcome
The current user experience involves the buyer purchasing a license from us and then inserting this license into FlowFuse. Ideally, this workflow should remain untouched. However, FlowFuse will be enhanced to recognize or provide two separate upload options for the different license types: one for FlowFuse Premium (or Teams) and another for FlowFuse Enterprise. Based on the license type uploaded, specific features will become available or remain locked. Features that are not available will behave exactly like they currently do in the Open Source edition.

```[tasklist]
### Tasks
- [x] Update license generator to ask for type field
- [x] Add type field to license log output and admin summary view
- [x] Update HA feature check to include license type check
- [x] Update SSO feature check to include license type check
```

**Comment by knolleary** [comment]
Given our existing license already provides all options, we need an approach that doesn't strip those users of features they have already bought an entitlement to.

Our current license structure does not include a 'type' field. We have three possible states:
 - no license
 - license
 - license with `dev: true` for developer mode

For this item, we will introduce a `type` field to the license. This can have the values:

 - `teams`
 - `enterprise`

**Proposal**: if we load a license without the type field, we will treat that as an `enterprise` license to ensure feature parity. Moving forward, we will not issue any licenses without the type field set to one of the above values.

In the code base, we have various places that simple check for the presence of a license. They will need to be updated to also check the type of the license (for the relevant features listed in the description above).

**Comment by hardillb** [comment]
And should a dev license automatically be `enterprise`?
