### ISSUE TITLE
Story: Modify the stack a project is configured to use

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#288]
### Epic

#285 

### Description

**As a:** User

**I want to:** Modify the stack a project is configured to use

**So that:** I can upgrade Node.js/Node-RED version

### Acceptance Criteria

 - [ ] ...

**Comment by sammachin** [comment]
Shouldn't this be as an *owner*

**Comment by knolleary** [comment]
- [ ] #437 covers the core changes
 - [ ] flowforge/flowforge-driver-localfs#37 - covers the localfs driver changes
 - [ ] flowforge/flowforge-driver-docker#17 - covers the docker driver changes

ToDo:

 - [ ] k8s driver changes
