### ISSUE TITLE
Rebrand Forge App

### ISSUE THREAD

**Issue by sammachin** [flowforge/flowforge#430]
### Description

This is to cover the work to replace the UI in the current Forge Application with the following aims:

- [ ] Parity with the existing feature set
- [ ] Consistency with the Corporate Brand of the FlowForge.com website
- [ ] Improved UX
- [ ] Reusable Design Components to speed future development
- [ ] Functional on Mobile devices, fully capable on tablet touchscreens (iPad) as much as practical on smaller "phones"
- [ ] Accessibility in line with industry best practices.

**Comment by ZJvandeWeg** [comment]
@sammachin @joepavitt It should be easier to estimate and schedule if this issue is split out in concrete things to change. There's been talks around a plan to rebrand the app, but these plans were never captured in issues. Who's working on it?

**Comment by joepavitt** [comment]
@ZJvandeWeg it's in the issues detailed in the checklist/description of this issue...

<img width="395" alt="Screenshot 2022-05-05 at 13 31 37" src="https://user-images.githubusercontent.com/99246719/166923408-bf045a40-39f7-4731-bfa9-356425d4b7af.png">
